package com.salabs.amanager.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SucursalAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSucursalAllPropertiesEquals(Sucursal expected, Sucursal actual) {
        assertSucursalAutoGeneratedPropertiesEquals(expected, actual);
        assertSucursalAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSucursalAllUpdatablePropertiesEquals(Sucursal expected, Sucursal actual) {
        assertSucursalUpdatableFieldsEquals(expected, actual);
        assertSucursalUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSucursalAutoGeneratedPropertiesEquals(Sucursal expected, Sucursal actual) {
        assertThat(expected)
            .as("Verify Sucursal auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSucursalUpdatableFieldsEquals(Sucursal expected, Sucursal actual) {
        assertThat(expected)
            .as("Verify Sucursal relevant properties")
            .satisfies(e -> assertThat(e.getNombre()).as("check nombre").isEqualTo(actual.getNombre()))
            .satisfies(e -> assertThat(e.getDireccion()).as("check direccion").isEqualTo(actual.getDireccion()))
            .satisfies(e -> assertThat(e.getTelefono()).as("check telefono").isEqualTo(actual.getTelefono()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSucursalUpdatableRelationshipsEquals(Sucursal expected, Sucursal actual) {}
}
